<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMo2B7m\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMo2B7m/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGMo2B7m.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGMo2B7m\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerGMo2B7m\appAppKernelDevDebugContainer([
    'container.build_hash' => 'GMo2B7m',
    'container.build_id' => '11c64e69',
    'container.build_time' => 1687954672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMo2B7m');
