<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container40a2Zrf\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container40a2Zrf/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container40a2Zrf.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container40a2Zrf\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container40a2Zrf\appAppKernelDevDebugContainer([
    'container.build_hash' => '40a2Zrf',
    'container.build_id' => '1bcc5324',
    'container.build_time' => 1687701059,
], __DIR__.\DIRECTORY_SEPARATOR.'Container40a2Zrf');
