<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXKnEI5\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXKnEI5/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEXKnEI5.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEXKnEI5\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerEXKnEI5\appAppKernelDevDebugContainer([
    'container.build_hash' => 'EXKnEI5',
    'container.build_id' => '8bb8839b',
    'container.build_time' => 1687951247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXKnEI5');
