<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBwNbVY\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBwNbVY/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBwNbVY.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBwNbVY\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerJBwNbVY\appAppKernelDevDebugContainer([
    'container.build_hash' => 'JBwNbVY',
    'container.build_id' => '1b0e0cea',
    'container.build_time' => 1687516181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBwNbVY');
