<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4dnneDh\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4dnneDh/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container4dnneDh.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container4dnneDh\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container4dnneDh\appAppKernelProdContainer([
    'container.build_hash' => '4dnneDh',
    'container.build_id' => '7c71df5b',
    'container.build_time' => 1687607814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4dnneDh');
